from __future__ import annotations

from typing import List, Optional
from sqlalchemy.orm import Session
from fastapi import HTTPException, status

from app.models.asset import Asset
from app.models.product import Product
from app.schemas.asset import AssetCreate
from app.services.cloudinary_service import delete_asset as cloudinary_delete_asset


def create_asset(db: Session, asset_in: AssetCreate) -> Asset:
    """
    Persists a new generated asset in the database.
    """
    db_asset = Asset(
        generation_job_id=asset_in.generation_job_id,
        product_id=asset_in.product_id,
        colorway=asset_in.colorway,
        format=asset_in.format,
        cloudinary_public_id=asset_in.cloudinary_public_id,
        cloudinary_url=asset_in.cloudinary_url,
        width=asset_in.width,
        height=asset_in.height
    )
    db.add(db_asset)
    db.commit()
    db.refresh(db_asset)
    return db_asset


def get_job_assets(db: Session, job_id: str) -> List[Asset]:
    """
    Retrieves all assets generated by a specific generation job.
    """
    return db.query(Asset).filter(Asset.generation_job_id == job_id).all()


def get_product_assets(
    db: Session,
    product_id: str,
    format_filter: Optional[str] = None,
    color_filter: Optional[str] = None
) -> List[Asset]:
    """
    Retrieves all assets for a given product with optional filtering by format and colorway.
    """
    query = db.query(Asset).filter(Asset.product_id == product_id)
    if format_filter:
        query = query.filter(Asset.format == format_filter)
    if color_filter:
        query = query.filter(Asset.colorway == color_filter)
    return query.order_by(Asset.created_at.desc()).all()


def delete_asset(db: Session, asset_id: str) -> bool:
    """
    Deletes an asset from the database and removes it from Cloudinary storage.
    """
    asset = db.query(Asset).filter(Asset.id == asset_id).first()
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Asset with id {asset_id} not found."
        )

    # Remove from Cloudinary
    try:
        cloudinary_delete_asset(asset.cloudinary_public_id)
    except Exception:
        pass

    db.delete(asset)
    db.commit()
    return True


def get_user_assets(
    db: Session,
    user_id: str,
    format_filter: Optional[str] = None,
    color_filter: Optional[str] = None,
    skip: int = 0,
    limit: int = 100
) -> List[Asset]:
    """
    Retrieves all assets belonging to products owned by the user,
    with optional format and colorway filtering.
    """
    query = db.query(Asset).join(Product).filter(Product.user_id == user_id)
    if format_filter and format_filter != "All":
        query = query.filter(Asset.format == format_filter)
    if color_filter:
        query = query.filter(Asset.colorway.ilike(f"%{color_filter}%"))
    return query.order_by(Asset.created_at.desc()).offset(skip).limit(limit).all()
