from __future__ import annotations

from typing import List, Optional
from fastapi import APIRouter, Depends, Query, status
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.core.security import get_current_user
from app.models.user import User
from app.schemas.asset import AssetResponse
from app.services.asset_service import (
    get_job_assets,
    get_product_assets,
    get_user_assets,
    delete_asset
)
from app.services.product_service import get_product

router = APIRouter(prefix="/assets", tags=["Assets"])


@router.get(
    "/",
    response_model=List[AssetResponse],
    status_code=status.HTTP_200_OK,
    summary="List all assets belonging to current user"
)
def list_user_all_assets(
    format: Optional[str] = Query(None, description="Filter by format e.g. 1:1, 4:5, 9:16, 16:9"),
    color: Optional[str] = Query(None, description="Filter by colorway"),
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=200),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> List[AssetResponse]:
    """
    Returns all generated and transformed media assets belonging to the authenticated user.
    """
    assets = get_user_assets(
        db=db,
        user_id=str(current_user.id),
        format_filter=format,
        color_filter=color,
        skip=skip,
        limit=limit
    )
    return [AssetResponse.model_validate(a) for a in assets]


@router.get(
    "/job/{job_id}",
    response_model=List[AssetResponse],
    status_code=status.HTTP_200_OK,
    summary="Get all assets generated by a specific job"
)
def list_job_assets(
    job_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> List[AssetResponse]:
    """
    Returns the complete list of assets produced by a generation job run.
    """
    assets = get_job_assets(db=db, job_id=job_id, user_id=str(current_user.id))
    return [AssetResponse.model_validate(a) for a in assets]


@router.get(
    "/product/{product_id}",
    response_model=List[AssetResponse],
    status_code=status.HTTP_200_OK,
    summary="Get all ready-to-use assets for a product"
)
def list_product_assets(
    product_id: str,
    format: Optional[str] = Query(None, description="Filter by format e.g. 1:1, 9:16"),
    color: Optional[str] = Query(None, description="Filter by colorway"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> List[AssetResponse]:
    """
    Returns all generated and transformed media assets for a given product gallery.
    """
    # Enforce product user isolation
    _ = get_product(db=db, product_id=product_id, user_id=str(current_user.id))

    assets = get_product_assets(
        db=db,
        product_id=product_id,
        format_filter=format,
        color_filter=color
    )
    return [AssetResponse.model_validate(a) for a in assets]


@router.delete(
    "/{asset_id}",
    status_code=status.HTTP_200_OK,
    summary="Delete an asset from database and Cloudinary"
)
def remove_asset(
    asset_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
) -> dict:
    """
    Deletes an asset record and cleans up stored files on Cloudinary.
    """
    delete_asset(db=db, asset_id=asset_id, user_id=str(current_user.id))
    return {"success": True, "message": f"Asset {asset_id} deleted successfully."}
